spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cshop
    username: root
    password: ly050131
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
